# steps:
#   # Único paso: Probar que el Dockerfile compila correctamente
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['build', '.', '-t', 'mi-app-prueba']

# options:
#   logging: CLOUD_LOGGING_ONLY

steps:
  # 1. Compilar la imagen usando tu Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'us-central1-docker.pkg.dev/TU_PROYECTO_ID/mi-repo-python/app-python:latest', 
      '.'
    ]

  # 2. Subir automáticamente la imagen a tu repositorio en Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'us-central1-docker.pkg.dev/TU_PROYECTO_ID/mi-repo-python/app-python:latest'
    ]

options:
  # Soluciona el error 'build.service_account' obligando a usar solo la consola web de GCP
  logging: CLOUD_LOGGING_ONLY